[package]
name = "ics23"
version = "0.6.4"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
exclude = ["codegen"]
description = "Merkle proof verification library - implements Cosmos ICS23 Spec"
repository = "https://github.com/confio/ics23/tree/master/rust"
license = "Apache-2.0"

[workspace]
members = ["codegen"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
prost = "0.7.0"
bytes = "1.0.1"
hex = "0.4.3"
sha2 = "0.9.3"
sha3 = "0.9.1"
ripemd160 = "0.9.1"
anyhow = "1.0.40"

serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
